apiVersion: v1
kind: Secret
metadata:
  name: web-api
  labels:
    kubernetes.courselabs.co: hackathon
type: Opaque
stringData:
  # JSON configuration file for the Widgetario web application
  api.json: |-
    {
      "Widgetario": {
        "ProductsApi": {
          # Internal Cluster URL for the Products API service
          "Url": "http://products-api.default.svc.cluster.local/products"
        },
        "StockApi": {
          # Internal Cluster URL for the Stock API service
          "Url": "http://stock-api.default.svc.cluster.local/stock"
        }
      }
    }
