apiVersion: v1
kind: Service
metadata:
  name: widgetario-web-internal
  labels:
    kubernetes.courselabs.co: hackathon
    app: widgetario
spec:
  ports:
    - name: http
      port: 80           # Service exposes port 80 for HTTP traffic
      targetPort: http   # Forwards traffic to container port named "http"
  selector:  
    app: widgetario     # Selects pods labeled with app=widgetario
    component: web      # and component=web to route traffic
  type: ClusterIP      # Internal cluster-only service (no external exposure)
