apiVersion: v1
kind: Service
metadata:
  name: elasticsearch # Service for Elasticsearch
  namespace: logging
spec:
  selector:    
    app: elasticsearch
  ports:
  - name: elasticsearch
    port: 9200  # Port exposed by the service
    targetPort: 9200    # Port on the container
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment  # Deployment for Elasticsearch
metadata:
  name: elasticsearch
  namespace: logging
spec:
  selector:
    matchLabels:
      app: elasticsearch  # Selector for the pods managed by this deployment
  template:
    metadata:
      labels:
        app: elasticsearch  # Labels for the pods
    spec:
      containers:
      - image: courselabs/elasticsearch:7.10
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: elasticsearch