apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ingress-nginx-controller     # DaemonSet name
  namespace: ingress-nginx           # Namespace for the DaemonSet
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/instance: ingress-nginx
        app.kubernetes.io/component: controller
    spec:
      containers:
        - name: controller
          image: k8s.gcr.io/ingress-nginx/controller:v1.2.0   # Controller image
          args:                                              # Controller startup arguments
            - /nginx-ingress-controller
            - --publish-service=ingress-nginx/ingress-nginx-controller-lb
            - --publish-service=ingress-nginx/ingress-nginx-controller-np
            - --election-id=ingress-controller-leader
            - --ingress-class=nginx
            - --controller-class=k8s.io/ingress-nginx
            - --configmap=ingress-nginx/ingress-nginx-controller
          securityContext:
            runAsUser: 101              # Run container as user ID 101
            allowPrivilegeEscalation: true
          env:                         # Environment variables with Pod metadata
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:                       # Expose HTTP and HTTPS ports
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
      serviceAccountName: ingress-nginx   # Use this ServiceAccount
