apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx                          # Name of the IngressClass
  labels:
    app.kubernetes.io/component: controller
    kubernetes.courselabs.co: hackathon
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"  # Marks this as the default IngressClass
spec:
  controller: k8s.io/ingress-nginx    # Controller managing this IngressClass
