apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: monitoring
  labels:  
    kubernetes.courselabs.co: hackathon
spec:
  selector:
    app: grafana   # Selector for the Grafana pods
  ports:
    - name: grafana
      port: 3000   # Port exposed by the service
      targetPort: grafana
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-np
  namespace: monitoring
  labels:  
    kubernetes.courselabs.co: hackathon
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      port: 3000
      targetPort: grafana
      nodePort: 30003  # NodePort for the Grafana service
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-creds
  namespace: monitoring
stringData:
  GF_SECURITY_ADMIN_USER: admin   # Grafana admin credentials
  GF_SECURITY_ADMIN_PASSWORD: labs  # Grafana admin credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: courselabs/grafana:8.0.5   # Grafana image
          name: grafana
          ports:
            - containerPort: 3000     # Port exposed by the Grafana container
              name: grafana
          envFrom:
            - secretRef:
                name: grafana-creds
          env:
            - name: GF_USERS_DEFAULT_THEME  # Default theme for Grafana
              value: "light"
          volumeMounts:
            - name: config-datasources
              mountPath: "/etc/grafana/provisioning/datasources"   # Mount path for Grafana configuration
              readOnly: true
      volumes:
        - name: config-datasources
          configMap:
            name: grafana-config
            items:
            - key: datasources.yaml   # Key in the ConfigMap
              path: datasources.yaml   # Path in the mounted volume