apiVersion: v1
kind: Secret
metadata:
  name: products-db-password           # Secret holding Postgres DB password
  labels:
    kubernetes.courselabs.co: hackathon
type: Opaque                          # Generic secret type
stringData:
  POSTGRES_PASSWORD: h4ckkath0n       # Password for Postgres user
  PGPASSWORD: h4ckkath0n              # Alternate env var for Postgres password
