apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api                      # Deployment name for stock API
  labels:
    kubernetes.courselabs.co: hackathon
    app: widgetario
spec:
  replicas: 2                         # Number of replicas
  selector:
    matchLabels:
      app: widgetario
      component: stock-api             # Selector for pods with this label
  template:
    metadata:
      labels: 
        app: widgetario
        component: stock-api
        hackathon: part-1
    spec:
      automountServiceAccountToken: false
      containers:
        - name: app
          image: widgetario/stock-api:21.03   # Container image
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: stock-api-connection      # Inject secrets as env variables
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 30
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 60
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 100Mi 
          securityContext:
            readOnlyRootFilesystem: true       # Enhance container security
          volumeMounts:
            - name: cache
              mountPath: "/cache"              # Mount ephemeral cache directory
      volumes:
        - name: cache
          emptyDir:
            medium: Memory                    # Use in-memory emptyDir volume for cache
