apiVersion: v1
kind: Service
metadata:
  name: products-db-primary
spec:
  selector:
    role: primary
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: products-db-secondary
spec:
  selector:
    role: secondary
  ports:
    - port: 5432
