apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-widgetario-local           # Ingress resource name
  labels:
    kubernetes.courselabs.co: hackathon
spec:
  rules:
    - host: api.widgetario.local       # Host to route traffic for
      http:
        paths:
          - path: /                    # Path prefix to match
            pathType: Prefix
            backend:
              service:
                name: products-api     # Backend service to forward traffic to
                port:
                  name: http           # Target service port name
